stages:
  - commitlint
  - build
  - tag

commitlint:
  stage: commitlint
  image: node:12
  rules:
    - if: '$CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
  allow_failure: true
  before_script:
    - npm install --save-dev @commitlint/{config-conventional,cli}
    - chmod +x commitconfig.sh
    - ./commitconfig.sh
  script:
    - npx commitlint --from=$CI_COMMIT_BEFORE_SHA

commitlint-default:
  stage: commitlint
  image: node:12
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  before_script:
    - npm install --save-dev @commitlint/{config-conventional,cli}
    - chmod +x commitconfig.sh
    - ./commitconfig.sh
  script:
    - npx commitlint --from=$CI_COMMIT_BEFORE_SHA

build-branch:
  image: docker:19.03.12
  stage: build
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

tag-latest:
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  image: docker:19.03.12
  stage: tag
  services:
    - docker:19.03.12-dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest