version: "3.8"
services:

  web:
    container_name: frontend-server
    build: .
    ports:
      - 8080:80
    networks:
     - backend-network

  backend-server:
    image: registry.gitlab.com/librefoodpantry/client-solutions/theas-pantry/guestinfosystem/guestinfobackend:main
    init: true
    ports:
      - 10001:10001
    environment:
      HOST_BASE_URL: http://localhost:10001
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network:
