version: "3.8"
services:

  frontend-server:
    image: registry.gitlab.com/librefoodpantry/client-solutions/theas-pantry/guestinfosystem/guestinfofrontend
    environment:
      BACKEND_BASE_URL: http://localhost:10001/v0
    ports:
      - 8080:80
    depends_on:
      - backend-server

  backend-server:
    image: registry.gitlab.com/librefoodpantry/client-solutions/theas-pantry/guestinfosystem/guestinfobackend:latest
    ports:
      - 10001:3000
    environment:
      HOST_BASE_URL: http://localhost:10001/v0
      MONGO_URI: mongodb://backend-database
    networks:
      - backend-network
    depends_on:
      - backend-database

  backend-database:
    image: mongo:4
    networks:
      - backend-network

networks:
  backend-network:
